In [1]:
import numpy

In [3]:
# 1 st question
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

# Expected Output:

# Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]
print("Original List:", original_list)

array_1d = np.array(original_list)
print("One-dimensional NumPy array:", array_1d)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [4]:
# 2 nd question
# 2. Create 3x3 Matrix (2?10)
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

# Expected Output:

# [[ 2 3 4] [ 5 6 7] [ 8 9 10]]
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
# 3 rd question
# Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

null_vector = np.zeros(10)
print("Original Null Vector:", null_vector)

null_vector[5] = 11
print("Updated Vector:", null_vector)

Original Null Vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [7]:
## 4 th question
# Write a NumPy program to create an array with values ranging from 12 to 38.

# Expected Output:

# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
array = np.arange(12, 38)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
# 5 th question
## Write a NumPy program to convert an array to a floating type.

# Sample output:

# Original array [1, 2, 3, 4]
import numpy as np
original_array = np.array([1, 2, 3, 4])
print("Original array:", original_array)


float_array = original_array.astype(float)
print("Array converted to float:", float_array)

Original array: [1 2 3 4]
Array converted to float: [1. 2. 3. 4.]


In [ ]:
# 6 th question
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

# Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]


celsius_values = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])
print("Values in Centigrade degrees:", celsius_values)

fahrenheit_values = celsius_values * 9/5 + 32
print("Values in Fahrenheit degrees:", fahrenheit_values)

Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [10]:
## 7 th question
# 7. Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.

# Expected Output:

# Original array: [10, 20, 30]

# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
original_array = np.array([10, 20, 30])
print("Original array:", original_array)

values_to_append = [40, 50, 60, 70, 80, 90]

new_array = np.append(original_array, values_to_append)
print("After append values to the end of the array:", new_array)


Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [11]:
# 8 th question.
# Array Statistical Functions (Do self-tudy)
# Create a random NumPy array of 10 elements and calculate the mean,
#  median, and standard deviation of the array.

random_array = np.random.randint(0, 101, size=10)
print("Random Array:", random_array)

mean = np.mean(random_array)
median = np.median(random_array)
std_dev = np.std(random_array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Random Array: [67 15 70 85 53 33 22 98 37 68]
Mean: 54.8
Median: 60.0
Standard Deviation: 26.053022857242496


In [13]:
## 9 th question
# Find min and max
# Create a 10x10 array with random values and find the minimum and maximum values.

random_array = np.random.randint(0, 101, size=10)
print("Random Array:", random_array)

mean = np.mean(random_array)
median = np.median(random_array)
std_dev = np.std(random_array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Random Array: [74 47 34 94 88 14 71 74 84 43]
Mean: 62.3
Median: 72.5
Standard Deviation: 24.95215421561834


In [14]:
# 10 th question
# Create a 3x3x3 array with random values.
array_3d = np.random.rand(3, 3, 3)
print("3x3x3 Random Array:\n", array_3d)

3x3x3 Random Array:
 [[[0.45634326 0.93869953 0.58979775]
  [0.88147685 0.14439506 0.56151051]
  [0.34032795 0.19252438 0.82057465]]

 [[0.96215676 0.34569705 0.35206398]
  [0.89197299 0.11729604 0.92180586]
  [0.96480478 0.36500007 0.72553065]]

 [[0.19556255 0.62380998 0.64497083]
  [0.57564145 0.3250877  0.69654716]
  [0.98229498 0.89067359 0.93706122]]]
